# Generated by Django 5.0.4 on 2024-05-01 14:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pret_ecole_python_mange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='acheteur',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='salle',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='type_budget',
        ),
        migrations.RemoveField(
            model_name='pret',
            name='date_pret',
        ),
        migrations.RemoveField(
            model_name='pret',
            name='date_retour_effective',
        ),
        migrations.RemoveField(
            model_name='pret',
            name='date_retour_prevue',
        ),
        migrations.RemoveField(
            model_name='pret',
            name='enseignant',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='numero',
        ),
        migrations.AddField(
            model_name='materiel',
            name='achete_par',
            field=models.CharField(default='Inconnu', max_length=100),
        ),
        migrations.AddField(
            model_name='materiel',
            name='etat',
            field=models.CharField(default='Bon', max_length=100),
        ),
        migrations.AddField(
            model_name='materiel',
            name='proprietaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels', to='pret_ecole_python_mange.enseignant'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='salle_stockage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels', to='pret_ecole_python_mange.salle'),
        ),
        migrations.AddField(
            model_name='pret',
            name='date_emprunt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pret',
            name='date_retour',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pret',
            name='emprunte_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prets', to='pret_ecole_python_mange.enseignant'),
        ),
        migrations.AddField(
            model_name='pret',
            name='salle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prets', to='pret_ecole_python_mange.salle'),
        ),
        migrations.AddField(
            model_name='salle',
            name='code',
            field=models.CharField(default='Inconnu', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='prenom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pret',
            name='materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prets', to='pret_ecole_python_mange.materiel'),
        ),
        migrations.CreateModel(
            name='Accessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessoires', to='pret_ecole_python_mange.materiel')),
            ],
        ),
        migrations.AddField(
            model_name='materiel',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels', to='pret_ecole_python_mange.budget'),
        ),
    ]
